### PR TITLE
Refactor of unified areas work to reduce redundant code

### PR DESCRIPTION
**Pull request by jamescw**

### CODE REVIEW

**Comment by jamescw** [comment]
DO NOT MERGE YET! :)

**Comment by lbassil** [comment]
I have applied this function after adding the new controls we added to the areas... I also added areas 5 and 6 and added the return statement to the function.

**Comment by jamescw** [comment]
@lbassil this one is no longer needed right?

We already deployed the refeactor

**Comment by lbassil** [comment]
Yes true... we already deployed this!

**Comment by jamescw** [comment]
Awesome! closing this one then

**Pull request closed without merging**
